inherit_from: .rubocop_todo.yml

require:
  - rubocop-capybara
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - bin/*
    - db/schema.rb

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - config/environments/*
    - config/initializers/simple_form_bootstrap.rb

Metrics/LineLength:
  Exclude:
    - config/initializers/devise.rb

Metrics/MethodLength:
  Max: 35
  Exclude:
    - db/migrate/*

Metrics/AbcSize:
  Max: 30
  Exclude:
    - db/migrate/*
