volumes:
  db_storage:
  
services:
  db:
    image: postgres:16.4
    restart: unless-stopped
    volumes:
      - db_storage:/var/lib/postgresql/data
    ports:
      - ${PG_PORT:-5432}:5432
    environment:
      - POSTGRES_USER=opengas
      - POSTGRES_PASSWORD=opengas

  redis:
    image: redis:7.4
    restart: unless-stopped
    ports:
      - ${REDIS_PORT:-6379}:6379
