default: &default
  adapter: postgresql
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 10 } %>
  host: <%= ENV.fetch('PG_HOST', 'localhost') %>
  port: <%= ENV.fetch('PG_PORT', '5432') %>
  username: <%= ENV.fetch('PG_USER', 'opengas') %>
  password: <%= ENV.fetch('PG_PASSWORD', 'opengas') %>
  database: <%= ENV.fetch('PG_DATABASE', "opengas_#{Rails.env}") %>
  encoding: unicode

development:
  primary:
    <<: *default

test:
  primary:
    <<: *default
    database: <%= ENV.fetch('PG_DATABASE', 'opengas_test') %>

production:
  primary:
    <<: *default
    password: <%= Rails.application.credentials.dig(:pg, :password) %>
