default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
  retries: 100
  default_transaction_mode: immediate

development:
  primary:
    <<: *default
    database: storage/db/development.sqlite3

test:
  primary:
    <<: *default
    database: storage/db/test.sqlite3

production:
  primary:
    <<: *default
    database: storage/db/production.sqlite3
