service: open-gas-dev

image: baldarn/open-gas

servers:
  web:
    hosts:
      - staging.opengas.eu
    labels:
      traefik.http.routers.open_gas.entrypoints: websecure
      traefik.http.routers.open_gas.rule: Host(`staging.opengas.eu`)
      traefik.http.routers.open_gas.tls.certresolver: letsencrypt

registry:
  username: baldarn
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY

asset_path: /rails/public/assets
