service: open-gas-staging

image: baldarn/open-gas

servers:
  web:
    hosts:
      - staging.opengas.eu
    labels:
      traefik.http.routers.open_gas.entrypoints: websecure
      traefik.http.routers.open_gas.rule: Host(`staging.opengas.eu`)
      traefik.http.routers.open_gas.tls.certresolver: letsencrypt

registry:
  username: baldarn
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD

# Use accessory services (secrets come from .env).
accessories:
  db-staging:
    image: postgres:16.4
    host: opengas.eu
    port: 5432
    env:
      clear:
        POSTGRES_DB: "opengas_production"
        POSTGRES_USER: "opengas"
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data

asset_path: /rails/public/assets
