default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
      # recurring_tasks:
      #   medical_certificate_reminder:
      #     class: MedicalCertificateReminderJob
      #     schedule: every day
      #   blsd_reminder:
      #     class: BlsdReminderJob
      #     schedule: every day

  workers:
    - queues:
        - urgent
        - default
      threads: 3
      processes: 1
      polling_interval: 1

development:
 <<: *default

test:
 <<: *default

production:
 <<: *default
